#!/bin/bash

echo -ne "HTTP/1.1 200 OK\r\n"
echo -ne "Content-Type: text/event-stream\r\n"
echo -ne "Cache-Control: no-cache\r\n"
echo -ne "Connection: keep-alive\r\n"
echo -ne "\r\n"

while true; do
	s0=$((1 + $RANDOM % 100))
	s1=$((1 + $RANDOM % 100))
	s2=$((1 + $RANDOM % 100))
	s3=$((1 + $RANDOM % 100))
	s4=$((1 + $RANDOM % 100))
	echo -ne "data: [$s0, $s1, $s2, $s3, $s4]\n\n" 2>/dev/null || exit 0
	sleep 1
done
